### PR TITLE
Add lots of double quotes

### LINKED ISSUE #1816: zowe-setup-certificates.sh doesn't work if 'key_alias' has a space
**USS keystore setup** with entry `KEYSTORE_ALIAS="alias with space"`
```
...
[: /u/stevenh/mani/runtime/bin/zowe-setup-certificates.sh 136: FSUM6807 expression syntax error
Creating certificates and keystores... STARTED
apiml_cm.sh --action setup has failed. See /u/stevenh/zowe/logs/zowe-setup-certificates-2020-12-02-11-09-35.log for more details
<then hangs>
```
log file contains:
```
Unexpected parameter: with
APIML Certificate Management
usage: apiml_cm.sh --action <action>

  <action> action to be done:
     - setup - setups APIML certificate management
     - new-service-csr - creates CSR for new service to be signed by external CA
     - new-service - adds new service signed by local CA or external CA
     - trust - adds a public certificate of a service to APIML truststore
     - trust-zosmf - adds public certificates from z/OSMF to APIML truststore
     - trust-keyring - adds a public certificate of a service to APIML keyring
     - clean - removes files created by setup
     - jwt-keygen - generates and exports JWT key pair

  Called with: --verbose --log /u/stevenh/zowe/logs/zowe-setup-certificates-2020-12-02-11-09-35.log --action setup --service-ext SAN=dns:winmvs3b.hursley.ibm.com,ip:9.20.5.48,dns:localhost.localdomain,dns:localhost,ip:127.0.0.1 --service-password password --service-alias alias with space --service-keystore /u/stevenh/junk/keystore/alias with space/alias with space.keystore --service-truststore /u/stevenh/junk/keystore/alias with space/alias with space.truststore --local-ca-filename /u/stevenh/junk/keystore/local_ca/localca
```
**keyring setup** with property `ZOWE_CERTIFICATE_LABEL="Label with spaces"`:
```
...
[: /u/stevenh/mani/runtime/bin/zowe-setup-certificates.sh 136: FSUM6807 expression syntax error
Creating certificates and keystores... STARTED
Generating certificates for the keyring is skipped.
Creating certificates and keystores... DONE
Detecting external root CA... STARTED
Illegal option:  with
..
```

### PR DESCRIPTION
**Pull request by stevenhorsman**
Signed-off-by: stevenhorsman <steven@uk.ibm.com>

#### Relevant issues
Attempt to fix #1816 

#### Changes proposed in this PR
- Add lots of double quotes to cope with variables having strings

### CODE REVIEW

**Comment by stevenhorsman** [comment]
@vit-tomica - we've had a couple of problems in from customers recently who have tried using alias/keystore directories with spaces in, resulting in zowe-setup-certificates failing. I've tried to put anything that could possibly have a space in inside double-quotes here, and might have gone over the top, but it seems to have helped the recreates of the issue I've tried and work ok.

**Comment by vit-tomica** [comment]
Looks Ok. Thanks!! 👍

**Review by vit-tomica — APPROVED** [review]

**Comment by vit-tomica** [comment]
Are you going to run it against the keyring test suite as well once Jenkins is up and running?

**Comment by stevenhorsman** [comment]
> Are you going to run it against the keyring test suite as well once Jenkins is up and running?

Yeah - I ran those tests last night, RACF and ACF2 passed, marist-3 has connection issues, so TSS failed, but I'll re-run and link before merging (and possibly wait for marist-3 to be back before committing).

**Comment by vit-tomica** [comment]
Ok, cool. 👍

**Comment by stevenhorsman** [comment]
Convenience tests: https://wash.zowe.org:8443/view/Zowe/job/zowe-install-test/view/change-requests/job/PR-1817/2/
keyring tests: https://wash.zowe.org:8443/view/Zowe/job/zowe-install-test/view/change-requests/job/PR-1817/3 - TSS failures due to marist-3 being unavailable.

**Pull request merged**
