### PR TITLE
Updating ZWEWRF03 workflow

### PR DESCRIPTION
**Pull request by abastyr**
Please check if your PR fulfills the following requirements. This is simply a reminder of what we are going to look for before merging your PR. If you don't know all of this information when you create this PR, don't worry. You can edit this template as you're working on it.

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Necessary documentation (if appropriate) have been added / updated
- [x] DCO signoffs have been added to all commits, including this PR

#### PR type
What type of changes does your PR introduce to Zowe? _Put an `x` in the box that applies to this PR. If you're unsure about any of them, don't hesitate to ask._ 
- [x] Bugfix 
- [ ] Feature 
- [ ] Other... Please describe:

#### Relevant issues

Fixes 

#### Changes proposed in this PR

- There were a couple of changes to the instance.env that were not reflected in the workflow. This update fixes that.

#### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

#### Does this PR do something the person installing Zowe should know about?

There are now way more variables. I have used the documentation to fill in the description, but there are some variables that have either no documentation or the documentation is very vague about their meaning.

---
* Affected function: _general area of interest_ *

---
* Description: _1 line description_ *

---
* Part: _name of customizable file involved_  *

---
_multi-line description_

#### Is there a related doc issue or Pull Request? 

Doc issue/PR number:

### CODE REVIEW

**Review by NayerNajafi — COMMENTED** [review]
@abastyr @pavelzlatnik , Thank you for updating ZWEWRF03 workflow. This is my observations after performing this workflow:

1. The workflow creation failed with this error 
image

Line 234 is related to **<default>IZUDFLT</default>** of variable **APIML_SECURITY_ZOSMF_APPLID** .
This line looks good and there is no syntax error, but not sure why it refers to this line as error.
Workflow is created properly after I deleted all lines related to variable APIML_SECURITY_ZOSMF_APPLID in ZWEWRF03.xml.

2. These Zowe instance variables are not defined in the workflow Step1:
JOBS_API_PORT, FILES_API_PORT, JES_EXPLORER_UI_PORT, MVS_EXPLORER_UI_PORT, USS_EXPLORER_UI_PORT
so that we need to set them manually when instance.env is created
image

**Comment by pavelzlatnik** [comment]
> @abastyr @pavelzlatnik , Thank you for updating ZWEWRF03 workflow. This is my observations after performing this workflow:
> 
> 1. The workflow creation failed with this error
>    image
> 
> Line 234 is related to **IZUDFLT** of variable **APIML_SECURITY_ZOSMF_APPLID** . This line looks good and there is no syntax error, but not sure why it refers to this line as error. Workflow is created properly after I deleted all lines related to variable APIML_SECURITY_ZOSMF_APPLID in ZWEWRF03.xml.
> 
> 1. These Zowe instance variables are not defined in the workflow Step1:
>    JOBS_API_PORT, FILES_API_PORT, JES_EXPLORER_UI_PORT, MVS_EXPLORER_UI_PORT, USS_EXPLORER_UI_PORT
>    so that we need to set them manually when instance.env is created
>    image

I have notified Adrian, this seems as a conflict between default value and regex expression

**Comment by abastyr** [comment]
It was a typo in the regular expressions. When working with the shell variables I for some reason then switched around `^` and `$` characters in the regex.

I have also added the missing variables and it's ready for a new review.

**Comment by NayerNajafi** [comment]
@abastyr, I have the same issue for line 234 after trying the latest version.
image

**Comment by abastyr** [comment]
Ah, yeah, sorry. Forgot to commit the change with the missing `+` in the regular expression. It should be fine now.

**Review by NayerNajafi — APPROVED** [review]
Thank you!

**Pull request merged**
