### PR TITLE
Hold off client certificate auth for this release

### PR DESCRIPTION
**Pull request by jandadav**
This will be added back when client cert auth is ready
The attribute was removed not to confuse users with new and undocumented property
Apiml can deal with this attributte missing.

### CODE REVIEW

**Comment by stevenhorsman** [comment]
I'm not saying that this PR is necessarily broken, but I ran the convenience test: https://wash.zowe.org:8443/view/Zowe/job/zowe-install-test/view/change-requests/job/PR-1771/2 and it all failed as the gateway service didn't start (no messages in the job output log that I could see, but it was deleted swiftly, so I may have missed it.
The start.sh still seemed to have `apiml.security.x509.enabled=${APIML_SECURITY_X509_ENABLED}` for the gateway, so I'm not sure if that causes any problems as the value isn't defined?

**Comment by stevenhorsman** [comment]
I managed to catch the error on the next run:
```
2020-11-06 13:49:43.950 <ZWEAGW1:main:67451> ZWESVUSR ERROR (o.s.b.SpringApplication) Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'corsMetadataProcessor' defined in URL [jar:file:/ZOWE/staging/usr/lpp/zowe/components/api-mediation/gateway-service.jar!/BOOT-INF/classes!/org/zowe/apiml/gateway/metadata/service/CorsMetadataProcessor.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'securityConfiguration' defined in URL [jar:file:/ZOWE/staging/usr/lpp/zowe/components/api-mediation/gateway-service.jar!/BOOT-INF/classes!/org/zowe/apiml/gateway/security/config/SecurityConfiguration.class]: Unsatisfied dependency expressed through constructor parameter 6; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'authProviderInitializer' defined in URL [jar:file:/ZOWE/staging/usr/lpp/zowe/components/api-mediation/gateway-service.jar!/BOOT-INF/classes!/org/zowe/apiml/gateway/security/config/AuthProviderInitializer.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'compoundAuthProvider' defined in URL [jar:file:/ZOWE/staging/usr/lpp/zowe/components/api-mediation/gateway-service.jar!/BOOT-INF/classes!/org/zowe/apiml/gateway/security/config/CompoundAuthProvider.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'x509AuthenticationProvider': Unsatisfied dependency expressed through field 'isClientCertEnabled'; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'boolean'; nested exception is java.lang.IllegalArgumentException: Invalid boolean value []
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1308)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1154)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$156.000000007E72C630.getObject(Unknown Source)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:846)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.zowe.apiml.gateway.GatewayApplication.main(GatewayApplication.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:593)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'securityConfiguration' defined in URL [jar:file:/ZOWE/staging/usr/lpp/zowe/components/api-mediation/gateway-service.jar!/BOOT-INF/classes!/org/zowe/apiml/gateway/security/config/SecurityConfiguration.class]: Unsatisfied dependency expressed through constructor parameter 6; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'authProviderInitializer' defined in URL [jar:file:/ZOWE/staging/usr/lpp/zowe/components/api-mediation/gateway-service.jar!/BOOT-INF/classes!/org/zowe/apiml/gateway/security/config/AuthProviderInitializer.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'compoundAuthProvider' defined in URL [jar:file:/ZOWE/staging/usr/lpp/zowe/components/api-mediation/gateway-service.jar!/BOOT-INF/classes!/org/zowe/apiml/gateway/security/config/CompoundAuthProvider.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'x509AuthenticationProvider': Unsatisfied dependency expressed through field 'isClientCertEnabled'; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'boolean'; nested exception is java.lang.IllegalArgumentException: Invalid boolean value []
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1308)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1154)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$156.000000007E72C630.getObject(Unknown Source)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:392)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1282020-11-06 13:49:47.452 <ZWEADS1:main:66843> ZWESVUSR INFO  (o.z.a.p.s.ServiceStartupEventHandler) ZWEAM000I Discovery Service started in 52.228 seconds
```

**Review by stevenhorsman — CHANGES_REQUESTED** [review]
The api-layer version needs updating to be compatible with this change and us getting passing test runs before we can merge this.

**Comment by jandadav** [comment]
You are right, thanks! I'll adjust on the APIML side

**Comment by jandadav** [comment]
We have adjusted the APIML snapshot where this prop gets ignored. I have executed the build so let's see when it gets to it. This PR should be merged prior 1.17 release.

**Comment by stevenhorsman** [comment]
convenience tests: https://wash.zowe.org:8443/view/Zowe/job/zowe-install-test/view/change-requests/job/PR-1771/4/
ptf tests: https://wash.zowe.org:8443/view/Zowe/job/zowe-install-test/view/change-requests/job/PR-1771/5/

**Review by stevenhorsman — APPROVED** [review]

**Pull request merged**
