### PR TITLE
APIML sanity test endpoint /services

### PR DESCRIPTION
**Pull request by pj892031**
Please check if your PR fulfills the following requirements. This is simply a reminder of what we are going to look for before merging your PR. If you don't know all of this information when you create this PR, don't worry. You can edit this template as you're working on it.

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Necessary documentation (if appropriate) have been added / updated
- [x] DCO signoffs have been added to all commits, including this PR

#### PR type
What type of changes does your PR introduce to Zowe? _Put an `x` in the box that applies to this PR. If you're unsure about any of them, don't hesitate to ask._ 
- [ ] Bugfix 
- [ ] Feature 
- [x] Other... Please describe: sanity test for APIML feature

#### Relevant issues

Fixes 

#### Changes proposed in this PR

- https://github.com/zowe/api-layer/pull/1005

#### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

#### Does this PR do something the person installing Zowe should know about?

---
* Affected function: APIML sanity test*

---
* Description: sanity test fo verification if APIML's endpoint /services is available *

---
* Part: APIML  *

---
This PR adds a sanity test if endpoint `/services` is accessible. It means it checks SAF resource APIML.SERVICES and its verification. It is a positive test, other tests are realized via JUnit in APIML.

#### Is there a related doc issue or Pull Request? 

Doc issue/PR number: 
https://github.com/zowe/docs-site/pull/1520

### CODE REVIEW

**Review by jandadav — APPROVED** [review]

**Comment by jandadav** [comment]
There is more work to be done but this PR should verify the default Zowe method of configuring and retrieving the service info. Let's merge it and we will raise issues for the remaining pieces.

**Review by FlappiTomic — APPROVED** [review]

**Review by jackjia-ibm — APPROVED** [review]
Thanks, LGTM.

Please fix DCO before merging.

**Comment by jandadav** [comment]
@FlappiTomic I have fixed the DCO. Are there further actions I need to take?

**Comment by FlappiTomic** [comment]
> @FlappiTomic I have fixed the DCO. Are there further actions I need to take?

I don't think so, looks good to me. I spinned a very quick build to eliminate some false alarms in the past.... after that we are good to go

**Comment by jandadav** [comment]
@FlappiTomic Thanks!

**Comment by jandadav** [comment]
@FlappiTomic Will you have time processing this PR?

**Pull request merged**
