### PR TITLE
Enhance ZWESECUR with rights for certificate mapping

### PR DESCRIPTION
**Pull request by achmelo**
Aim of this PR is to provide necessary permissions for main Zowe server to read from identity mapping service. This functionality will be provided as a REST API via ZSS and will be secured by API ML JWT. 

Please check if your PR fulfills the following requirements. This is simply a reminder of what we are going to look for before merging your PR. If you don't know all of this information when you create this PR, don't worry. You can edit this template as you're working on it.

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Necessary documentation (if appropriate) have been added / updated
- [ ] DCO signoffs have been added to all commits, including this PR

#### PR type
What type of changes does your PR introduce to Zowe? _Put an `x` in the box that applies to this PR. If you're unsure about any of them, don't hesitate to ask._ 
- [ ] Bugfix 
- [x] Feature 
- [ ] Other... Please describe:

#### Relevant issues

Fixes https://github.com/zowe/api-layer/issues/827

#### Changes proposed in this PR

- 

#### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

#### Does this PR do something the person installing Zowe should know about?

The documentation PR: TBD

---
* Affected function: mapping x509 client certificate to zOS identity

---
* Description: This security configuration is necessary for API ML to be able to map client certificate to zOS identity.

---
* Part: _name of customizable file involved_  *
`./workflows/templates/ZWESECUR.vtl`

---
This security setup is done by submitting `ZWESECUR` JCL member. For users upgrading from version 1.15 and lower, follow the configuration steps below.

If you use RAFC, follow these steps to verify and update permission in FACILITY class.
1. verify user `ZWESVUSR` has read access

    ```
    RLIST FACILITY IRR.RUSERMAP AUTHUSER
    ```

2. add user `ZWESVUSR` permission to read
    ```
    PERMIT IRR.RUSERMAP CLASS(FACILITY) ACCESS(READ) ID(ZWESVUSR)
    ```
3. activate changes
    ```
    SETROPTS RACLIST(FACILITY) REFRESH
    ```
If you use ACF2, follow these steps to verify and update permission in FACILITY class.
1. verify user `ZWESVUSR` has read access
    ```      
    SET RESOURCE(FAC) 
    LIST LIKE(IRR-)
    ```    
2. add user `ZWESVUSR` permission to read
    ```
    RECKEY IRR.RUSERMAP ADD(SERVICE(READ) ROLE(&STCGRP.) ALLOW)
    ```
If you use TSS, follow these steps to verify and update permission in FACILITY class.
1. verify user `ZWESVUSR` has read access
    ```      
    TSS WHOHAS IBMFAC(IRR.RUSERMAP)
    ```    
2. add user `ZWESVUSR` permission to read
    ```
    TSS PER(ZWESVUSR) IBMFAC(IRR.RUSERMAP) ACCESS(READ)
    ```

#### Is there a related doc issue or Pull Request? 

Doc issue/PR number: 

https://github.com/zowe/docs-site/pull/1438

### CODE REVIEW

**Comment by achmelo** [comment]
smpe https://wash.zowe.org:8443/job/zowe-install-test/view/change-requests/job/PR-1714/9/
convenience build https://wash.zowe.org:8443/job/zowe-install-test/view/change-requests/job/PR-1714/7/

**Comment by stevenhorsman** [comment]
The updates done here need some documentation in the "Does this PR do something the person installing Zowe should know about?" section of the PR as this will go into the HOLDDATA of the PTF. It probably should document the delta that someone can manually do to bring a previous install up-to-date, or suggest re-running ZWESECUR.

**Comment by achmelo** [comment]
We added this information do docs-site https://github.com/zowe/docs-site/pull/1438/files . It is mentioned in "Is there a related doc issue or Pull Request?" . Do you think we need to provide it somewhere else or add more info there?

**Comment by stevenhorsman** [comment]
> We added this information do docs-site https://github.com/zowe/docs-site/pull/1438/files . It is mentioned in "Is there a related doc issue or Pull Request?" . Do you think we need to provide it somewhere else or add more info there?

Unfortunately we need a copy here as well. The doc is great and absolutely required, but the PR template is used to generate the HOLDDATA.

**Comment by achmelo** [comment]
I am struggling to find some example of whats need to be done from previous PRs. I did update of the "Does this PR do something the person installing Zowe should know about?" , is it now correct?

**Comment by stevenhorsman** [comment]
Sorry, out instructions aren't that obvious and I've never done a HOLDDATA update myself, so I wasn't very clear. #1537 is an example of a PR which had it, so might be useful. I think that the only bit missing from yours is the part: which I guess is `workflows/templates/ZWESECUR.vtl`, so I updated it for you.

**Comment by stevenhorsman** [comment]
With respect to the downstream work that relies on these changes I'm not sure they will work as I don't think that the id has the correct permissions to run all of these commands, but that's a separate issue #1734.

**Review by stevenhorsman — APPROVED** [review]
With the caveat that I'm definitely not a security systems expert, and it has been reviewed by someone who is, it looks plausible to me.

**Pull request merged**
