### PR TITLE
IZUSVR read access to BPX.JOBNAME

### PR DESCRIPTION
**Pull request by John-A-Davies**
Add IZUSVR to IZUADMIN as the users to check for READ access to BPX.JOBNAME, and reflect this in the error message.

### CODE REVIEW

**Comment by stevenhorsman** [comment]
We should be reading in the user name and group from the yaml file as per https://github.com/zowe/zowe-install-packaging/issues/314

**Comment by John-A-Davies** [comment]
I'd like to keep the fix for #736 (which hits every user, and needs to be done anyway, because they will always see false errors if IZUSVR is not explictly able to read BPX.JOBNAME) separate from #314 (which hits only those few who don't use IZUSVR/IZUADMIN, and is a pervasive code change)

**Comment by OnnoVdT** [comment]
Isn't it &ZOWEUSER who needs this permit? And if so, shouldn't we do this in ZWESUCUR?

**Comment by stevenhorsman** [comment]
@OnnoVdT - I think this is just a very old PR relating to the verify script which is broken and removed from doc, so we can close it.

**Comment by OnnoVdT** [comment]
@stevenhorsman 
While it's true this is old and parts of it no longer apply, the BPX.JOBNAME permit itself is still very valid. If you don';t have the permit, you cannot start tasks with a given name, and that's what &ZOWEUSER now does for all the child servers.

Not sure if we should reopen this one and adjust title, or open a new one.

https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.bpxb200/fclass.htm
BPX.JOBNAME

Controls which users are allowed to set their own job names by using the _BPX_JOBNAME environment variable or the inheritance structure on spawn. Users with READ or higher permissions to this profile can define their own job names.

**Comment by stevenhorsman** [comment]
@OnnoVdT we have https://github.com/zowe/zowe-install-packaging/issues/1049 to cover adding BPX.JOBNAME to ZWESECUR - this item was about changing the messaging in a script that is no longer based on an id that we aren't using, which is why I closed it.

**Pull request closed without merging**
