### PR TITLE
Re-instate checks on Zowe STC and its port assignments

### PR DESCRIPTION
**Pull request by John-A-Davies**
Signed-off-by: John Davies <daviesja@uk.ibm.com>

This is the first step of the rework of this script.  It reinstates the checks on the job names of the Zowe STCs, and the checks that the right ports are assigned to each one.

Further checks will be reinstated in the next update.

### CODE REVIEW

**Comment by stevenhorsman** [comment]
I'm seeing lots of errors when I run zowe-verify.sh:

```/u/stevenh/570/runtime/scripts:>zowe-verify.sh
Script zowe-verify.sh started

Info: ZOWE_ROOT_DIR environment variable is empty
Info: ZOWE_ROOT_DIR environment variable is now set to /u/stevenh/570/runtime

Check SAF security settings are correct
Error: userid IZUSVR is not in RACF group IZUADMIN
Check IZUSVR has UPDATE access to BPX.SERVER and BPX.DAEMON
Error: profile BPX.SERVER is not defined
Error: User IZUSVR does not have UPDATE access to profile BPX.SERVER
Error: profile BPX.DAEMON is not defined
Error: User IZUSVR does not have UPDATE access to profile BPX.DAEMON
Check IZUSVR/IZUADMIN has at least READ access to BPX.JOBNAME
Warning: User IZUSVR does not have access to profile BPX.JOBNAME
You will not be able to set job names using the _BPX_JOBNAME environment variable
OK: opercmd is available

Check Zowe jobs are running
Error: Expecting 1 job(s) for ZOWESSV1, found       0 
Error: Expecting 1 job(s) for ZOWESSV12, found       0 
CEE5206S The signal SIGINT was received.
/u/stevenh/570/runtime/scripts:>zowe-start.sh
MV3B      2019219  09:41:47.69             ISF031I CONSOLE MYCONS ACTIVATED
MV3B      2019219  09:41:47.69            -S ZOWESVR,SRVRPATH='/u/stevenh/570/runtime',JOBNAME=ZOWESSV1
ISF754I Command 'SET CONSOLE MYCONS' generated from associated variable ISFCONS.
ISF776I Processing started for action 1 of 1.
ISF769I System command issued, command text: S ZOWESVR,SRVRPATH='/u/stevenh/570/runtime',JOBNAME=ZOWESSV1.
ISF766I Request completed, status: NO RESPONSE RECEIVED.
Start command issued, check SDSF job log ...
/u/stevenh/570/runtime/scripts:>zowe-verify.sh
Script zowe-verify.sh started

Info: ZOWE_ROOT_DIR environment variable is empty
Info: ZOWE_ROOT_DIR environment variable is now set to /u/stevenh/570/runtime

Check SAF security settings are correct
Error: userid IZUSVR is not in RACF group IZUADMIN
Check IZUSVR has UPDATE access to BPX.SERVER and BPX.DAEMON
Error: profile BPX.SERVER is not defined
Error: User IZUSVR does not have UPDATE access to profile BPX.SERVER
Error: profile BPX.DAEMON is not defined
Error: User IZUSVR does not have UPDATE access to profile BPX.DAEMON
Check IZUSVR/IZUADMIN has at least READ access to BPX.JOBNAME
Warning: User IZUSVR does not have access to profile BPX.JOBNAME
You will not be able to set job names using the _BPX_JOBNAME environment variable
OK: opercmd is available

Check Zowe jobs are running
Error: Expecting 1 job(s) for ZOWESSV1, found      10 
Error: Expecting 1 job(s) for ZOWESSV12, found       0 
Error: Expecting 1 job(s) for ZOWESAGW1, found       0 
Error: Expecting 1 job(s) for ZOWESADS1, found       0 
Error: Expecting 1 job(s) for ZOWESAAC1, found       0 
Error: Expecting 8 job(s) for ZOWESDS1, found       0 
Error: Expecting 1 job(s) for ZOWESEAJ1, found       0 
Error: Expecting 1 job(s) for ZOWESEAD1, found       0 
Error: Expecting 1 job(s) for ZOWESEUJ1, found       0 
Error: Expecting 1 job(s) for ZOWESEUD1, found       0 
Error: Expecting 1 job(s) for ZOWESEUU1, found       0 

Check Zowe ports are assigned to jobs
EZZ2355I 'ZOWESAGW1' specified for -E must be 8 characters or less
Error: Port 41554 not assigned to ZOWESAGW1
EZZ2355I 'ZOWESADS1' specified for -E must be 8 characters or less
Error: Port 41553 not assigned to ZOWESADS1
EZZ2355I 'ZOWESAAC1' specified for -E must be 8 characters or less
Error: Port 41552 not assigned to ZOWESAAC1
Error: Port 41544 not assigned to ZOWESDS1
Error: Port 41542 not assigned to ZOWESDS1
EZZ2355I 'ZOWESEAJ1' specified for -E must be 8 characters or less
Error: Port 41545 not assigned to ZOWESEAJ1
EZZ2355I 'ZOWESEAD1' specified for -E must be 8 characters or less
Error: Port 41547 not assigned to ZOWESEAD1
EZZ2355I 'ZOWESEUJ1' specified for -E must be 8 characters or less
Error: Port 41546 not assigned to ZOWESEUJ1
EZZ2355I 'ZOWESEUD1' specified for -E must be 8 characters or less
Error: Port 41548 not assigned to ZOWESEUD1
EZZ2355I 'ZOWESEUU1' specified for -E must be 8 characters or less
Error: Port 41550 not assigned to ZOWESEUU1
Error: Found 0 ports assigned, expecting 10

Check ZSS server is running
ZSS server job name is 0
Error: Job 0 is not running as a started task

Check Node is at right version
Info: Found in /etc/profile
OK: version is v8.16.0

Check version of z/OS
Info: release of z/OS is RELEASE z/OS 02.03.00 LICENSE = z/OS
OK: version 02.03.00 is supported

Check IZUFPROC
OK

Check zosmfServer is ready to run a smarter planet
ls: /var/zosmf/data/logs/zosmfServer/logs/messages.log: EDC5111I Permission denied.


Check servers are up

Check jobs AXR CEA ICSF CSF
OK

Check relevant -s extattr bits
OK

Check relevant -p extattr bits
OK

Check files are executable
-r-xr-x---   1 STEVENH  IZUADMIN    1422 Jul 17 17:06 install-app.sh
-r-xr-x---   1 STEVENH  IZUADMIN    4062 Jul 17 17:06 nodeCluster.sh
-r-xr-x---   1 STEVENH  IZUADMIN    4040 Jul 17 17:06 nodeServer.sh
-r-xr-x---   1 STEVENH  IZUADMIN    1483 Jul 17 17:06 zlux-install-script.sh
-rwxrwx---   1 STEVENH  IZUADMIN 2236416 Jul 31 14:33 zssServer
-r-xr-x---   1 STEVENH  IZUADMIN    3925 Jul 17 17:06 zssServer.sh
-r-xr-x---   1 STEVENH  IZUADMIN    6269 Oct 26  1985 z-schema
-r-xr-x---   1 STEVENH  IZUADMIN    1579 Oct 26  1985 uuid
-r-xr-x---   1 STEVENH  IZUADMIN    4427 Oct 26  1985 semver
-r-xr-x---   1 STEVENH  IZUADMIN    4948 Jan  5  2017 esparse.js
-r-xr-x---   1 STEVENH  IZUADMIN    7744 Jul 13  2018 esvalidate.js
-r-xr-x---   1 STEVENH  IZUADMIN    2727 Oct 26  1985 js-yaml.js
-r-xr-x---   1 STEVENH  IZUADMIN     731 Dec 26  2014 cmd.js
-r--r-----   1 STEVENH  IZUADMIN     315 Dec 26  2014 usage.txt
-r-xr-x---   1 STEVENH  IZUADMIN      45 Jan  5  2018 tsc
-r-xr-x---   1 STEVENH  IZUADMIN      50 Jan  5  2018 tsserver
-r-xr-x---   1 STEVENH  IZUADMIN    5738 Dec 21  2018 sshpk-conv
-r-xr-x---   1 STEVENH  IZUADMIN    4011 Apr 22  2016 sshpk-sign
-r-xr-x---   1 STEVENH  IZUADMIN    3553 Oct 12  2018 sshpk-verify
-rwxr-x---   1 STEVENH  IZUADMIN     985 Jun  7 14:43 which
-rwxr-x---   1 STEVENH  IZUADMIN    4418 Jun  7 14:43 semver
-rwxr-x---   1 STEVENH  IZUADMIN    4418 Jun  7 14:54 semver
-rwxr-x---   1 STEVENH  IZUADMIN     985 Jun  7 14:54 which
-rwxr-x---   1 STEVENH  IZUADMIN     985 Jun  7 16:03 which
-rwxr-x---   1 STEVENH  IZUADMIN    4418 Jun  7 16:03 semver
Error: the bin files above in /u/stevenh/570/runtime are not readable and executable

Script zowe-verify.sh finished```

**Comment by John-A-Davies** [comment]
1.  For "Error: userid IZUSVR is not in RACF group IZUADMIN", this works for me.  Perhaps your $PATH does not have `/bin`, which is where tsocmd is located.

2.  For "Error: Expecting 1 job(s) for ZOWESSV1, found       0 ", this is because we're halfway towards the new STC naming scheme.  Previously, we had  
`ZOWE_PREFIX=ZOWE` and `ZOWE_API_GW=${ZOWE_PREFIX}AGW1` etc, 
then we moved to 
`ZOWE_PREFIX=ZOWEx`, with `ZOWE_API_GW=${ZOWE_PREFIX}AGW` (no suffix number).  Your test config has 
`ZOWE_PREFIX=ZOWES` which is fine, but it also has `ZOWE_API_GW=${ZOWE_PREFIX}AGW1` etc, which is not what my script's looking for, and it makes half the jobnames > 8 letters,  so you get
`EZZ2355I 'ZOWESAGW1' specified for -E must be 8 characters or less`
and JES changes their names anyway.  

3.  For "Error: Job 0 is not running as a started task", this is a known issue; #538.  The solution is pending this one, #570.  I'll add #538 to #570 if you prefer.

**Comment by John-A-Davies** [comment]
1.  For "Error: userid IZUSVR is not in RACF group IZUADMIN", you should run the script as a user (such as TSTRADM) who is authorised to list group IZUADMIN.  Admittedly, the error message should be corrected to emit
`NOT AUTHORIZED TO LIST BASE INFORMATION FOR GROUP IZUADMIN`
and subsequent checks requiring that authorisation should be abandoned.  However, that part of the script has not been changed.  

2.  For "Error: Expecting 1 job(s) for ZOWESSV1, found 0 ", the current 1.4.0 version of Zowe effectively limits `ZOWE_PREFIX` to 4 chars, and the suffixes of the STCs are defined in `run-zowe.template.sh` and `zowe-start.template.sh`.  `zowe-verify.sh` depends on these fixed values, as it says on line 387 of that script.  
If you use `ZOWE_PREFIX=ZOWE` it should work.  Alternatively, `ZOWE_PREFIX=ZWEx` should also work, allowing you a free letter x to identify your own Zowe instance.

3.  I will include the #538 fix tomorrow.

**Comment by John-A-Davies** [comment]
I've changed it to use the new STC naming scheme #582.

If the userid you use to test it does not have authority to list RACF groups, you will get the 11 errors at the start, as noted by @stevenhorsman.  

This PR also fixes #538.

**Pull request merged**
