### PR TITLE
Staging

### PR DESCRIPTION
**Pull request by raymondyanli**
Please check if your PR fulfills the following requirements. This is simply a reminder of what we are going to look for before merging your PR. If you don't know all of this information when you create this PR, don't worry. You can edit this template as you're working on it.

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Necessary documentation (if appropriate) have been added / updated
- [ ] DCO signoffs have been added to all commits, including this PR

#### PR type
What type of changes does your PR introduce to Zowe? _Put an `x` in the box that applies to this PR. If you're unsure about any of them, don't hesitate to ask._ 
- [ ] Bugfix 
- [ ] Feature 
- [ x] Other... Please describe:
Adding new systems for zowe pipeline

#### Relevant issues

No

Fixes 

#### Changes proposed in this PR

We have new vms need to be in zowe pipeline installation 

#### Does this PR introduce a breaking change?

- [ ] Yes
- [ x] No

#### Does this PR do something the person installing Zowe should know about?

---
* Affected function: _general area of interest_ *

---
* Description: _1 line description_ *

---
* Part: _name of customizable file involved_  *

---
_multi-line description_

#### Is there a related doc issue or Pull Request? 

Doc issue/PR number:

### CODE REVIEW

**Comment by raymondyanli** [comment]
@jackjia-ibm this PR is for adding new systems in zowe pipeline so that we can install zowe on them.

**Comment by jackjia-ibm** [comment]
@raymondyanli do you need these 2 hosts in `playbooks/hosts`?

**Comment by raymondyanli** [comment]
@jackjia-ibm Yes. they need to be in hosts. updated this request.

**Comment by jackjia-ibm** [comment]
@raymondyanli could you please follow instruction here https://github.com/zowe/zowe-install-packaging/pull/1558/checks?check_run_id=944981521 to solve the DCO failure? Then it's good to merge I think.

**Comment by raymondyanli** [comment]
closed this PR since a new PR created.

**Pull request closed without merging**
