### PR TITLE
Enable client certificate authentication on environment with ACF2

### LINKED ISSUE #1779: Authentication with client certificates on ACF2
*Customer content*

**Is your feature request related to a problem? Please describe.**
API ML can provide authentication with valid client certificate.  This is being tested on marist-1 with RACF. To be sure that users with ACF2 can leverage this functionality, this needs to be tested also on ACF2. There are some prerequisites in security system configuration before we can run the tests.

**Describe the solution you'd like**
There are few steps:
1. Allow user, which runs API ML (ZWESVUSR), generate Passticket for zOSMF APPL ID.
2. Allow user, which runs API ML (ZWESVUSR), to use R_usermap(map certificate to zOS identity)
   - this step is partly done in ZWESECUR, but user running scripts doesnt have permissions
3. Create profile SO.ZWETOKEN and USER.ZWETOKEN in CRYPTOZ with ACCESS(CONTROL) for user (ZWESVUSR)
  - there is a how to in zowe-docs but we were not able to add certificate to token when access was UPDATE
https://docs.zowe.org/stable/user-guide/configure-certificates-keystore.html#using-web-tokens-for-sso-on-zlux-and-zss
 
**Describe alternatives you've considered**
client certificate will not be tested on ACF2 - this is not recommended 

**Additional context**
This setup has been done for RACF as a part of #1713 
Issue related to this: #1778 
---
*Engineering team info (eg https://github.com/zowe/explorer-jes/issues/4)*

**As a** [type of user],  
**I want** [some goal]  
**so that** [some reason].

*Details/notes*  
[Detail - implementation notes]

#### Acceptance Criteria

**Scenario 1:* [Title]  
*Given* [context]  
   *And* [some more context]...  
*When* [event]  
*Then* [outcome]  
    *And* [another outcome]...

### PR DESCRIPTION
**Pull request by achmelo**
Signed-off-by: achmelo <a.chmelo@gmail.com>

Please check if your PR fulfills the following requirements. This is simply a reminder of what we are going to look for before merging your PR. If you don't know all of this information when you create this PR, don't worry. You can edit this template as you're working on it.

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Necessary documentation (if appropriate) have been added / updated
- [ ] DCO signoffs have been added to all commits, including this PR

#### PR type
What type of changes does your PR introduce to Zowe? _Put an `x` in the box that applies to this PR. If you're unsure about any of them, don't hesitate to ask._ 
- [ ] Bugfix 
- [ ] Feature 
- [x] Other... Please describe: Existing feature tested on 1 env, goal is to verify for all security systems.

#### Relevant issues

Fixes #1779 
#### Changes proposed in this PR

- 

#### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

#### Does this PR do something the person installing Zowe should know about?

---
* Affected function: _general area of interest_ *

---
* Description: _1 line description_ *

---
* Part: _name of customizable file involved_  *

---
_multi-line description_

#### Is there a related doc issue or Pull Request? 

Doc issue/PR number:

### CODE REVIEW

**Comment by MarkAckert** [comment]
The certificate generation on TSS is looking good in the latest build run. The tests failed, but everything seems OK when I tried to log in manually. Can you review build 57 and browse the Zowe install on zzow03?

**Comment by MarkAckert** [comment]
Actually, our build on TSS may have been overwritten or used a fallback configuration. I'd like to lock ACF/TSS systems down next week (once RC is built), so we can have more time with a given system state.

**Comment by achmelo** [comment]
> The certificate generation on TSS is looking good in the latest build run. The tests failed, but everything seems OK when I tried to log in manually. Can you review build 57 and browse the Zowe install on zzow03?

This new way of transferring certificate to dataset seems work fine and certificate is valid. There is some problem with ZSS configuration, I am going to take a look.

**Comment by achmelo** [comment]
I split this and moved TSS part to https://github.com/zowe/zowe-install-packaging/pull/2025

**Comment by jackjia-ibm** [comment]
@achmelo I'm not sure how this PR is connected to PR2025. After I merged PR2025, I noticed this PR was also automatically marked as merged and branch was deleted. I didn't really read through this PR and not sure if it's ready. And the interesting part it says it's merged, but I couldn't find the changes of this PR in `staging` branch.

So I guess please continue work on your branch and create a new PR when it's ready. Thank you!

**Pull request merged**
