### PR TITLE
Update fixed version number

### LINKED ISSUE #1531: api-mediation pax file renamed to 0.8.4 during build
I've noticed that in the build (including release) the mediation pax is called `api-mediation-package-0.8.4.pax`. I've just spotted that `.pax/pre-packaging.sh` has this value hardcoded in it, so this should be fixed

### PR DESCRIPTION
**Pull request by stevenhorsman**
#### Relevant issues
Fixes #1531 

#### Changes proposed in this PR
- Replace hard coded version number with the zowe version. This isn't perfect, but there is a large overlap between the api-ml version and overall zowe and we don't seem to have access to the correct version anywhere at this point.

### CODE REVIEW

**Comment by stevenhorsman** [comment]
convenience test: https://wash.zowe.org:8443/view/Zowe/job/zowe-install-test/view/change-requests/job/PR-1753/2
ptf tests: https://wash.zowe.org:8443/view/Zowe/job/zowe-install-test/view/change-requests/job/PR-1753/3

**Review by jackjia-ibm — APPROVED** [review]
Thanks Steve! This is better than before, but maybe we can just remove the version?

**Comment by stevenhorsman** [comment]
I'm happy with removing the version number and have made the code changes, but can't test due to the CLI issue blocking runs

**Comment by jackjia-ibm** [comment]
I’m thinking it could only affect how to find the apiml pax during install. Another way to verify is building smpe. Other than that, I think this should be good without an end-to-end test. 👍

**Comment by stevenhorsman** [comment]
smpe build was green, so I'll merge without the test. thanks!

**Pull request merged**
