### PR TITLE
Zwesecur2

### LINKED ISSUE #848: Modify test pipeline to execute ZWESECUR, rather than run zowe-config-stc.sh
Now we have the JCL we need to test it in our pipeline

### PR DESCRIPTION
**Pull request by John-A-Davies**
Please check if your PR fulfills the following requirements. This is simply a reminder of what we are going to look for before merging your PR. If you don't know all of this information when you create this PR, don't worry. You can edit this template as you're working on it.

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Necessary documentation (if appropriate) have been added / updated
- [ ] DCO signoffs have been added to all commits, including this PR

#### PR type
What type of changes does your PR introduce to Zowe? _Put an `x` in the box that applies to this PR. If you're unsure about any of them, don't hesitate to ask._ 
- [ ] Bugfix 
- [y] Feature 
- [ ] Other... Please describe:

#### Relevant issues

Fixes #848 

#### Changes proposed in this PR

- RACF setup is now done by ZWESECUR.jcl instead of in zowe-install-apf-server.sh

#### Does this PR introduce a breaking change?

- [ ] Yes
- [ x] No

#### Does this PR do something the person installing Zowe should know about?

---
* Affected function: _general area of interest_ *

---
* Description: _1 line description_ *
The installing user will have to customise ZWESECUR.jcl
---
* Part: _name of customizable file involved_  *
ZWESECUR.jcl
---
_multi-line description_

#### Is there a related doc issue or Pull Request? 

Doc issue/PR number:

### CODE REVIEW

**Comment by John-A-Davies** [comment]
I think this is now ready for your review.

**Comment by stevenhorsman** [comment]
Should the call to zowe-copy-xmem.sh in zowe-install.sh be removed as I don't think it is needed anymore?

**Comment by stevenhorsman** [comment]
I think zowe-install.sh:13 also needs to updated to `ZOWE_GROUP=ZWEADMIN` now

**Comment by John-A-Davies** [comment]
With  `ZOWE_GROUP=ZWEADMIN`, `zowe-install.sh -i` gives
```
FSUM6185 chgrp: group "ZWEADMIN" is unknown
```
because ZWESECUR.jcl has not been run at this point, so that needs to be run before `chgrp`.

**Comment by stevenhorsman** [comment]
> With `ZOWE_GROUP=ZWEADMIN`, `zowe-install.sh -i` gives
> 
> ```
> FSUM6185 chgrp: group "ZWEADMIN" is unknown
> ```
> 
> because ZWESECUR.jcl has not been run at this point, so that needs to be run before `chgrp`.

That's an interesting one with a bit of chicken and egg. I think in the short term the best thing is to detect if the group hasn't been created and echo a message to the user to run ZWESECUR and then issue the chgrp command

**Comment by John-A-Davies** [comment]
I've implemented those suggestions.

**Comment by John-A-Davies** [comment]
The install-test now passes cleanly (https://wash.zowe.org:8443/job/zowe-install-test/view/change-requests/job/PR-151/26/), and test of SMP/E worked on ukzowe3

**Pull request merged**
