### PR TITLE
ZIP 1239 - Add validate only mode

### PR DESCRIPTION
**Pull request by stevenhorsman**
## PR type
- [X] Feature

#### Relevant issues
Depends on #1334 
Implements #1239 

#### Changes proposed in this PR
- Add validation mode of Zowe.
If `VALIDATE_ONLY=true` is set in instance.env then launching Zowe will exit after the validation stage. This lets a Zowe administration run a check of whether all the Zowe install's component validation checks work without having to actually start any of the components.

Doc issue: https://github.com/zowe/docs-site/issues/1180

### CODE REVIEW

**Comment by stevenhorsman** [comment]
Convenience tests: https://wash.zowe.org:8443/job/zowe-install-test/view/change-requests/job/PR-1335/2/
smp/e ptf tests: https://wash.zowe.org:8443/job/zowe-install-test/view/change-requests/job/PR-1335/3/

**Comment by stevenhorsman** [comment]
Manual testing:
```
/u/stevenh/1335/instance-dir:>echo "VALIDATE_ONLY=true" >> instance.env
/u/stevenh/1335/instance-dir:>cat instance.env
#!/bin/sh

# Note this script is executed like a shell script, so can have embedded variables
...
VALIDATE_ONLY=true
```

STDOUT:
```
Appending JAVA_HOME/bin to the PATH...
Appending NODE_HOME/bin to the PATH...
OK: Node is working
Error 0: NODE Version 8.16.1 is not compatible with Zowe. Please use a different version. See https://docs.zowe.org/stable/troubleshoot/app-framework/app-known-issues.html#desktop-apps-fail-to-load for more details
1 errors were found during validatation, please check the message, correct any properties required in /u/stevenh/1335/instance-dir/instance.env and re-launch Zowe
1 errors were found during validatation, please check the message, correct any properties required in /u/stevenh/1335/instance-dir/instance.env and re-launch Zowe
Validation complete - VALIDATE_ONLY mode set to true, so Zowe will not start.
```

**Comment by Joe-Winchester** [comment]
@stevenhorsman - there are some conflicts that I can't see how I can resolve easily, apologies

**Comment by stevenhorsman** [comment]
@Joe-Winchester - the dependencies are due to PR #1334 which this requires not being merged.
Sorry, I'm having trouble understanding:
> Looks great - one thing I found doing some testing is that when I added lines to `validate.sh` scripts like "echo "JRW This is an error" it stopped Zowe but possibly now how I had thought it would, e.g.
> 
> ```
> Error 0: JRW
> Error: /u/winchj/zowe-1.11.0/runtime/bin/internal/run-zowe.sh 127: FSUM7351 not found
> ```
> 
> Is there an API way to do something in an error script that flags an error as occuring or is that waiting on the APIness of the error.sh script ?
That not found error doesn't look great. Can you let me know the changes you made that triggered it?

**Pull request merged**
