### PR TITLE
PR-1851 for RC

### PR DESCRIPTION
**Pull request by 1000TurquoisePogs**
This is identical to https://github.com/zowe/zowe-install-packaging/pull/1851 except pointing to RC. Please close one or the other if the duplication is not needed.

### CODE REVIEW

**Comment by stevenhorsman** [comment]
@NakulManchanda - there were failures in the docker test for this PR: https://wash.zowe.org:8443/view/Zowe/job/zowe-install-test/view/change-requests/job/PR-1853/3/consoleFull

**Comment by NakulManchanda** [comment]
hi @stevenhorsman 
i can add them to ignore if thats better and less confusing.
These are new tests, not yet covered for docker.
image

**Comment by NakulManchanda** [comment]
Failing test are ignored for now, will address same in https://github.com/zowe/zowe-install-packaging/issues/1859

**Comment by stevenhorsman** [comment]
Given that this has been waiting for 5 days for a review and is holding up Rc I'm going to merge it without one. I think from @jackjia-ibm 's comments on #1851 that there aren't any stop ship (or stop RC) issues, so will get it included today whilst we have a chance.

**Pull request merged**
