### PR TITLE
set APIML_SECURITY_AUTHORIZATION_PROVIDER to endpoint

### PR DESCRIPTION
**Pull request by jackjia-ibm**
Signed-off-by: Jack (T.) Jia <jack-tiefeng.jia@ibm.com>

### CODE REVIEW

**Comment by jandadav** [comment]
Try setting all of these variables:
 

    -Dapiml.security.authorization.provider=${APIML_SECURITY_AUTHORIZATION_PROVIDER:-} \ < endpoint
    -Dapiml.security.authorization.endpoint.enabled=${APIML_SECURITY_AUTHORIZATION_ENDPOINT_ENABLED:-false} \ < true
    -Dapiml.security.authorization.endpoint.url=${APIML_SECURITY_AUTHORIZATION_ENDPOINT_URL} \ < https://${ZOWE_EXPLORER_HOST}:${GATEWAY_PORT}/zss/api/v1/saf-auth in instance.env already

**Comment by FlappiTomic** [comment]
Test still failed, I think we may need to add in -Dapiml.security.authorization.endpoint.url=${APIML_SECURITY_AUTHORIZATION_ENDPOINT_URL} \ < https://${ZOWE_EXPLORER_HOST}:${GATEWAY_PORT}/zss/api/v1/saf-auth in instance.env already

as David suggested.

**Comment by FlappiTomic** [comment]
Latest test shows response 500 now, instead 403 before.
```
1) test endpoint /services and its authentication
           with authenticated user:
  
          AssertionError: expected 500 to equal 200
          + expected - actual
  
          -500
          +200
```

**Comment by jackjia-ibm** [comment]
Based on test https://wash.zowe.org:8443/view/Zowe/job/zowe-install-test/view/change-requests/job/PR-2154/6/consoleText, it got this response:

```
    2021-05-19T15:54:16.157Z zowe-sanity-test:apiml:utils 1cd658fc-d183-43b0-9e33-dee2be128a19 response status: 500
    2021-05-19T15:54:16.157Z zowe-sanity-test:apiml:utils 1cd658fc-d183-43b0-9e33-dee2be128a19 response statusText:
    2021-05-19T15:54:16.157Z zowe-sanity-test:apiml:utils 1cd658fc-d183-43b0-9e33-dee2be128a19 response headers: { vary: 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers',
      'x-content-type-options': 'nosniff',
      'x-xss-protection': '1; mode=block',
      'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
      pragma: 'no-cache',
      expires: '0',
      'content-type': 'application/json',
      'transfer-encoding': 'chunked',
      date: 'Wed, 19 May 2021 15:54:15 GMT',
      connection: 'close' }
    2021-05-19T15:54:16.158Z zowe-sanity-test:apiml:utils 1cd658fc-d183-43b0-9e33-dee2be128a19 response data: { messages:
       [ { messageType: 'ERROR',
           messageNumber: 'ZWEAT603E',
           messageContent: 'Endpoint `https://localhost:7554/zss/api/v1/saf-auth` is not properly configured',
           messageKey: 'org.zowe.apiml.security.common.auth.saf.endpoint.endpointImproprietyConfigure' } ] }
```

In the docker log section, I can see these values:

```
ZOWE_EXPLORER_HOST=localhost
GATEWAY_PORT=7554
APIML_SECURITY_AUTHORIZATION_PROVIDER=endpoint
APIML_SECURITY_AUTHORIZATION_ENDPOINT_URL=https://localhost:7554/zss/api/v1/saf-auth
APIML_SECURITY_AUTHORIZATION_ENDPOINT_ENABLED=true
```

So we have all the required variables in place.

I believe the issue is that zss is not registered to discovery when we run Docker build. The static registration file only exists on z/OS side. This PR may solve this issue https://github.com/zowe/zlux-app-server/pull/167/files.

**Comment by FlappiTomic** [comment]
>  on test https://wash.zowe.org:8443/view/Zowe/job/zowe-install-test/view/change-requests/job/PR-2154/6/consoleText, it got this response:
> 
> ```
>     2021-05-19T15:54:16.157Z zowe-sanity-test:apiml:utils 1cd658fc-d183-43b0-9e33-dee2be128a19 response status: 500
>     2021-05-19T15:54:16.157Z zowe-sanity-test:apiml:utils 1cd658fc-d183-43b0-9e33-dee2be128a19 response statusText:
>     2021-05-19T15:54:16.157Z zowe-sanity-test:apiml:utils 1cd658fc-d183-43b0-9e33-dee2be128a19 response headers: { vary: 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers',
>       'x-content-type-options': 'nosniff',
>       'x-xss-protection': '1; mode=block',
>       'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
> ```

I see thanks for the explaination

**Comment by jandadav** [comment]
Further down in the Gateway's log, I can see that the endpoint code is trying to reach out for the `/zss/api/v1/saf-auth/APIML.SERVICES/READ` route but cannot find it. I agree with Jack that if ZSS is not in discovery service, it won't work.

```
2021-05-19 15:54:16.151 <ZWEAGW1:https-jsse-nio-0.0.0.0-7554-exec-6:3379> zowe ERROR (o.a.c.c.C.[.[.[.[dispatcherServlet]) Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.zowe.apiml.security.common.auth.saf.EndpointImproprietyConfigureException: Endpoint https://localhost:7554/zss/api/v1/saf-auth is not properly configured.] with root cause
    org.springframework.web.client.HttpClientErrorException$NotFound: 404 : [{"messages":[{"messageType":"ERROR","messageNumber":"ZWEAM104E","messageContent":"The endpoint you are looking for '/zss/api/v1/saf-auth/APIML.SERVICES/READ' could not be located","messageKey":"org.zowe.apiml.common.endPointNotFound"}]}]
            at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:113)
            at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:184)
            at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:125)
            at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
            at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:780)
            at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:738)
            at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:672)
            at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:581)
            at org.zowe.apiml.security.common.auth.saf.SafResourceAccessEndpoint.hasSafResourceAccess(SafResourceAccessEndpoint.java:55)
            at org.zowe.apiml.security.common.auth.saf.SafMethodSecurityExpressionRoot.hasSafResourceAccess(SafMethodSecurityExpressionRoot.java:45)
            at org.zowe.apiml.security.common.auth.saf.SafMethodSecurityExpressionRoot.hasSafServiceResourceAccess(SafMethodSecurityExpressionRoot.java:49)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at org.springframework.expression.spel.support.ReflectiveMethodExecutor.execute(ReflectiveMethodExecutor.java:129)
            at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:139)
            at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:95)
            at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:117)
            at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:308)
            at org.springframework.security.access.expression.ExpressionUtils.evaluateAsBoolean(ExpressionUtils.java:26)
            at org.springframework.security.access.expression.method.ExpressionBasedPreInvocationAdvice.before(ExpressionBasedPreInvocationAdvice.java:59)
            at org.springframework.security.access.prepost.PreInvocationAuthorizationAdviceVoter.vote(PreInvocationAuthorizationAdviceVoter.java:72)
            at org.springframework.security.access.prepost.PreInvocationAuthorizationAdviceVoter.vote(PreInvocationAuthorizationAdviceVoter.java:40)
            at org.springframework.security.access.vote.AffirmativeBased.decide(AffirmativeBased.java:63)
            at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:233)
            at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:65)
            at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
            at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
            at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
            at org.zowe.apiml.gateway.services.ServicesInfoController$$EnhancerBySpringCGLIB$$9fbb6ca2.getServices(<generated>)
```

**Comment by jackjia-ibm** [comment]
This is needed for docker test. Once ZSS is registered correctly with gateway, we can reenable the test and verify.

**Pull request merged**
