### PR TITLE
Set zowe env vars without directly running .profile

### PR DESCRIPTION
**Pull request by John-A-Davies**
Signed-off-by: John Davies <daviesja@uk.ibm.com>

### CODE REVIEW

**Comment by stevenhorsman** [comment]
$PROFILE should be removed, or better set to .zowe_profile - then some of the other changes aren’t required
Remove the section about touch ~/$PROFILE
If you created zowe_profile will it have execute permission?

**Comment by John-A-Davies** [comment]
The 'source' command, i.e. the dot command, does not require its target to be executable.

**Comment by John-A-Davies** [comment]
I removed the `touch` of PROFILE, so we don't create an unnecessary file.  PROFILE is set by `zowe-install-sh` anyway so I removed that too.

**Comment by stevenhorsman** [comment]
Can you commit the zowe-install.sh change to this PR?
Also zowe-install-test:uninstall-zowe.sh reference to profile will need updating

**Comment by stevenhorsman** [comment]
Convention also seems to be to use _ rather that - in hidden profile files

**Comment by John-A-Davies** [comment]
I should have said  "PROFILE is _already_ set by the existing zowe-install-sh script."

**Pull request merged**
