### PR TITLE
iframe updates uss mvs

### PR DESCRIPTION
**Pull request by NakulManchanda**
Signed-off-by: Nakul Manchanda <nakul.manchanda@ibm.com>

Add support for new destination property to iframe pluginDefinition.json

Please check if your PR fulfills the following requirements. This is simply a reminder of what we are going to look for before merging your PR. If you don't know all of this information when you create this PR, don't worry. You can edit this template as you're working on it.

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Necessary documentation (if appropriate) have been added / updated
- [ ] DCO signoffs have been added to all commits, including this PR

#### PR type
What type of changes does your PR introduce to Zowe? _Put an `x` in the box that applies to this PR. If you're unsure about any of them, don't hesitate to ask._ 
- [ ] Bugfix 
- [ ] Feature 
- [ ] Other... Please describe:

#### Relevant issues

Fixes 

#### Changes proposed in this PR

- 

#### Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

#### Does this PR do something the person installing Zowe should know about?

---
* Affected function: _general area of interest_ *

---
* Description: _1 line description_ *

---
* Part: _name of customizable file involved_  *

---
_multi-line description_

#### Is there a related doc issue or Pull Request? 

Doc issue/PR number:

### CODE REVIEW

**Comment by NakulManchanda** [comment]
1) Add new test all `/iframe` path needs authentication cookie header otherwise 404
2) Refactor Tests for:
- `MVS`
- `USS`
3) Added test to zlux path to `iframe-adapter` and `logger` (which has implicit version 0.9) in path
Both used by iframe plugins, so added them as smoke test

**Comment by NakulManchanda** [comment]
tried manual install with new zlux changes to staging and new explorer installation using `appfwPlugins` and new `pluginDefinition.json` template with destination property included in explorers pax as well.

**Comment by NakulManchanda** [comment]
https://wash.zowe.org:8443/view/Zowe/job/zowe-install-test/view/change-requests/job/PR-1890/4/

**Comment by NakulManchanda** [comment]
its ready for merge for release v1.19

**Comment by stevenhorsman** [comment]
This doesn't pass the tests

**Review by jackjia-ibm — APPROVED** [review]
LGTM, thanks Nakul!

**Pull request merged**
