### PR TITLE
Capture Swagger API Definitions

### PR DESCRIPTION
**Pull request by CarsonCook**
Tests have not been added for this specific change, as this change is adding a test case that generates the Swagger API definition files. I have manually tested and it seems to have worked. The json files in this PR are the ones generated by the new test. I also ran jenkins install jobs for the pax and smpe-ptf builds that have passed, as well as a job for the API generation ([pax](https://wash.zowe.org:8443/job/zowe-install-test/view/change-requests/job/PR-1596/129/),[ smpe-ptf](https://wash.zowe.org:8443/job/zowe-install-test/view/change-requests/job/PR-1596/130/), [api-gen](https://wash.zowe.org:8443/job/zowe-install-test/view/change-requests/job/PR-1596/155/)).

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Necessary documentation (if appropriate) have been added / updated
- [x] DCO signoffs have been added to all commits, including this PR

#### PR type
What type of changes does your PR introduce to Zowe? _Put an `x` in the box that applies to this PR. If you're unsure about any of them, don't hesitate to ask._ 
- [ ] Bugfix 
- [x] Feature 
- [ ] Other... Please describe:

#### Relevant issues

Resolves [Docs #537](https://github.com/zowe/docs-site/issues/537)

#### Changes proposed in this PR

Adds test scope that installs and starts Zowe, then runs a nodejs "test" file that requests and stores Swagger API definition files. Then, a new stage, `API Documentation Check-In`, pushes these definitions files to Github. This way, docs.zowe.org can link to `petstore.swagger.io?url={api-def-in-github}` to provide up-to-date documentation on what APIs are available.

The files are only pushed to Github if this test scope is ran on the master branch with the `generate api documentation` test scope.

#### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

#### Does this PR do something the person installing Zowe should know about?

No.

#### Is there a related doc issue or Pull Request? 

Doc issue/PR number: [#537](https://github.com/zowe/docs-site/issues/537)

### CODE REVIEW

**Comment by stevenhorsman** [comment]
It looks reasonable to me, did you decide that you wanted to store the api doc in the zowe-install-packaging build, rather than as part of the doc repo then? I don't think you'll get any of the doc versioning linking to the correct version this way.

**Comment by CarsonCook** [comment]
@stevenhorsman Thanks for catching that, I just forgot to add that functionality in. Should be working now.

@nannanli Adding you here as fyi. When `zowe-install-test` pipeline is run on the master branch, with test scope `generate api documentation`, it will check-in the datasets, jobs, gateway, and zlux plugin Swagger API definition files into the `api_definitions` in the top level of `docs-sites` on the `docs-staging` branch.

**Comment by stevenhorsman** [comment]
Looking good. Can you link the connivence and smpe ptf test runs please so we can see there are no regressions please?

**Comment by CarsonCook** [comment]
> Looking good. Can you link the connivence and smpe ptf test runs please so we can see there are no regressions please?
[Convenience run](https://wash.zowe.org:8443/job/zowe-install-test/view/change-requests/job/PR-1596/166/) and [spme ptf run](https://wash.zowe.org:8443/job/zowe-install-test/view/change-requests/job/PR-1596/165/)

**Review by stevenhorsman — APPROVED** [review]
LGTM

**Pull request merged**
