### PR TITLE
Add started task names to Zowe USS processes

### PR DESCRIPTION
**Pull request by vasev01**
- New configuration parameter `prefix`
- Add component codes from [#385](https://github.com/zowe/zowe-install-packaging/issues/385#issuecomment-489555612) to each process

### CODE REVIEW

**Comment by plavjanik** [comment]
What happens when the user ID does not have access to BPX.JOBNAME?

**Comment by vasev01** [comment]
@plavjanik Nothing happens, job names will not change. The documentation will state this.

**Comment by plavjanik** [comment]
image

**Comment by patbossman** [comment]
Here's a jumping off point for BPX.* (including JOBNAME).
https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.bpxb200/fclass.htm

**Comment by patbossman** [comment]
IANASP ... but I believe the RACF would be:
activate facility class, permit BPX.JOBNAME, refresh facility class:
`SETROPTS CLASSACT(FACILITY) RACLIST(FACILITY)
PERMIT BPX.JOBNAME CLASS(FACILITY) ID(<userid>) ACCESS(READ)
SETROPTS RACLIST(FACILITY) REFRESH`

**Comment by vasev01** [comment]
@plavjanik Here are changes in the docs: https://github.com/zowe/docs-site/pull/573/files?file-filters%5B%5D=.md&hide-deleted-files=true&owned-by%5B%5D=#diff-631b43e6cb2233eb3ef020fd5dfff2f3R149

**Comment by IgorCATech** [comment]
Created a new PR to speed up the process of publishing 
https://github.com/zowe/docs-site/pull/590

**Comment by vasev01** [comment]
Closing. Rework PR #531

**Pull request closed without merging**
