### PR TITLE
define GIMDTS jobparm lines

### PR DESCRIPTION
**Pull request by jackjia-ibm**
Signed-off-by: Jack (T.) Jia <jack-tiefeng.jia@ibm.com>

Please check if your PR fulfills the following requirements. This is simply a reminder of what we are going to look for before merging your PR. If you don't know all of this information when you create this PR, don't worry. You can edit this template as you're working on it.

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Necessary documentation (if appropriate) have been added / updated
- [X] DCO signoffs have been added to all commits, including this PR

#### PR type
What type of changes does your PR introduce to Zowe? _Put an `x` in the box that applies to this PR. If you're unsure about any of them, don't hesitate to ask._ 
- [X] Bugfix 
- [ ] Feature 
- [ ] Other... Please describe:

#### Relevant issues

Fixes SMPE build failed on GIMDTS step:

```
IEF472I GIMDTS MARKER PTF@FB80 - COMPLETION CODE - SYSTEM=722 USER=0000 REASON=00000000
```

#### Changes proposed in this PR

- Increase JOBPARM LINES.

#### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jackjia-ibm** [comment]
Tried 2 builds (https://wash.zowe.org:8443/view/Zowe/job/zowe-install-packaging/job/users%252Fjack%252Ffix-smpe/) and seems this solves the issue. Thanks @NayerNajafi

**Comment by OnnoVdT** [comment]
github is having issues to let me sign in, but I have a comment about the PR
Successful builds indicate it's not a problem now, but there is more than just lines that can cause this
https://www.ibm.com/support/knowledgecenter/SSLTBW_2.4.0/com.ibm.zos.v2r4.ieab600/iea3b6_Relationship_to_other_parameters70.htm
 
So at least add a comment line to the JCL mentioning the other parms, or add with appropriate values
 
Onno
Onno Van den Troostz/OS specialist for Developer for z/OSIBM z Systems[+1] (720) 342-6760onno@us.ibm.comIBM
 
 
----- Original message -----From: "Jack (T.) Jia" <notifications@github.com>To: zowe/zowe-install-packaging <zowe-install-packaging@noreply.github.com>Cc: OnnoVdT <onno@us.ibm.com>, Review requested <review_requested@noreply.github.com>Subject: [EXTERNAL] Re: [zowe/zowe-install-packaging] define GIMDTS jobparm lines (#1865)Date: Mon, Jan 4, 2021 12:26 PM 
 
Tried 2 builds (https://wash.zowe.org:8443/view/Zowe/job/zowe-install-packaging/job/users%252Fjack%252Ffix-smpe/) and seems this solves the issue. Thanks @NayerNajafi

**Comment by jackjia-ibm** [comment]
Had contacted Marist to make this change permanent on the server. But it's good to have in case this value changed in the future. PTF build and test passed: https://wash.zowe.org:8443/job/zowe-install-test/job/PR-1865/4/.

**Review by stevenhorsman — APPROVED** [review]
Looks fine to me.

**Comment by jackjia-ibm** [comment]
Going to merge the PR since Onno may have issue on login and we had discussed the changes offline. @OnnoVdT please let me know if you want any changes. Thanks a lot for the helps.

**Pull request merged**
