### PR TITLE
TLS support for zss

### PR DESCRIPTION
**Pull request by lchudinov**
#### PR type
This PR makes zss to use https protocol by default.
- [ ] Bugfix 
- [x] Feature 

#### Relevant issues

Fixes https://github.com/zowe/zlux/issues/632

#### Does this PR introduce a breaking change?

- [X] Yes
- [ ] No

APIML has a hardcoded URL pointing to zss using `http` protocol.

### CODE REVIEW

**Comment by NakulManchanda** [comment]
Hi guys,

I checked convenience build on my local system, very basic scenarios looks great
- login to zowe desktop works - 8554 & 7554
- tried basic app like zlux-edior
- api catalog is displaying zss as registered service

@NayerNajafi will help check the latest PR build, on keyring, & signed certificate system by tomm morning EST
 
 FYI @lchudinov @1000TurquoisePogs

**Comment by NakulManchanda** [comment]
For caching service test suite error on last test run, i have merged the latest from staging, 
hopefully we pass those caching service tests on next run
Thanks!

**Comment by NayerNajafi** [comment]
@NakulManchanda I installed PR https://zowe.jfrog.io/artifactory/libs-snapshot-local/org/zowe/1.20.0-PR-2010/zowe-1.20.0-pr-2010-6-20210315194531.pax

My observations:
1- error messages in log:
```
CEE3204S The system detected a protection exception (System Completion Code=0C4).
         From entry point jsonObjectGetString at statement 1552 at compile unit offset +00000060 at entry offset
         +00000060 at address 0E37DE20.
```     
```
ZWEADS1:Thread-21:16777266> ZWESVUSR WARN  (o.z.a.d.s.ServiceDefinitionProcessor) ZWEAD702W Unable to process static API definition data: '/SYSTEM/var/zowe120/instance/workspace/api-mediation/api-defs/zss_zss_yml.yml' - 'No content to map due to end-of-input
at ÝSource: (StringReader); line: 2, column: 1¨'
```
2- ZSS server is not started, 8542 is not listening, there is no ZWES1014I ZIS status - 'Ok'
3- Cannot access Desktop {"message":"ZSS 500 Internal Server Error"},"reason":"ConnectionError"
4- API Catalog displays ZSS as a registered service
image

**Comment by lchudinov** [comment]
@NayerNajafi What was inside of your `zowe-certificates.env` ?

**Comment by NayerNajafi** [comment]
@lchudinov 
```
KEY_ALIAS="ZWECA"                                             
KEYSTORE_PASSWORD="password"                                  
KEYRING_OWNER="ZWESVUSR"                                      
KEYRING_NAME="ALIAS-RING"                                     
KEYSTORE="safkeyring:////${KEYRING_OWNER}/${KEYRING_NAME}"    
KEYSTORE_TYPE="JCERACFKS"                                     
TRUSTSTORE="safkeyring:////${KEYRING_OWNER}/${KEYRING_NAME}"  
EXTERNAL_ROOT_CA="IBMInternalRootCA"                          
EXTERNAL_CERTIFICATE_AUTHORITIES=""                           
LOCAL_CA="localca"                                            
ZOWE_APIM_VERIFY_CERTIFICATES=false                           
SSO_FALLBACK_TO_NATIVE_AUTH=true                              
PKCS11_TOKEN_NAME=""                                          
PKCS11_TOKEN_LABEL=""                                    
```

**Review by 1000TurquoisePogs — APPROVED** [review]
I'm told this fixes our tests except something in apiml which cant be fixed until this is merged, so I'm merging it and we'll fix as we go.

**Pull request merged**
