### PR TITLE
Support command typo

### LINKED ISSUE #3164: Zwe support --target-dir -> package always in /tmp/
**Describe the bug**
It seems ```--target-dir``` is ignored.

**To Reproduce**
1. ```zwe support -c /x/zowe/zowe.yaml --target-dir /x/zowe/tmp```
2. Last line of zwe support command: ```>> Zowe support package is generated as /tmp/zwe-support.2022-11-22-09-13-22.pax.Z```

**Expected behavior**
Package created in target dir, in this example ```/x/zowe/tmp```

**Additional context**
I have tried following with the same result:
- ```zwe support -c /z/zowe.yaml --target-dir /z/userID/zowe/tmp```
- ```zwe support --target-dir /z/userID/zowe/tmp -c /z/zowe.yaml```
 -```zwe support --target-dir "/z/userID/zowe/tmp" -c /z/zowe.yaml```

It seems, that in [index.sh](https://github.com/zowe/zowe-install-packaging/blob/0d8d5bf395041167f07bb047f34708e3ba261405/bin/commands/support/index.sh#L19)
```target_dir="${ZWE_CLI_PARAMETER_CONFIG_TARGET_DIR}"```
should be 
```target_dir="${ZWE_CLI_PARAMETER_TARGET_DIR}"```

I can fix that.

### PR DESCRIPTION
**Pull request by Martin-Zeithaml**
Signed-off-by: Martin Zeithaml <Martin.Zeithaml@broadcom.com>

Please check if your PR fulfills the following requirements. This is simply a reminder of what we are going to look for before merging your PR. If you don't know all of this information when you create this PR, don't worry. You can edit this template as you're working on it.

- [x] DCO signoffs have been added to all commits, including this PR

#### PR type

- [x] Bugfix 

#### Relevant issues
Fixes #3164

#### Changes proposed in this PR

See #3164  

#### Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by Martin-Zeithaml** [comment]
I have added simple conversion of target directory to absolute path. Without the conversion, it will not work for current directory, e.g.:  `zwe support -c /zowe/zowe.yaml --target-dir .`

**Review by 1000TurquoisePogs — APPROVED** [review]

**Comment by 1000TurquoisePogs** [comment]
Looks great!
Test systems are having issues right now, but will merge when possible.

**Comment by Martin-Zeithaml** [comment]
Just a small note, if the wrong directory is used, the pax file will be created in the current directory. 
The question is, should we (for wrong directory) terminate the script or use temporary directory or use the current directory?
I don't see a problem with current solution, because the last line of this script is printing a location of created pax file.

**Comment by 1000TurquoisePogs** [comment]
I think you are right, its fine as long as it prints the location.

**Pull request merged**
