### PR TITLE
APIML SSO Support

### PR DESCRIPTION
**Pull request by timgerstel**
Signed-off-by: Timothy Gerstel <tim.gerstel@gmail.com>

Please check if your PR fulfills the following requirements. This is simply a reminder of what we are going to look for before merging your PR. If you don't know all of this information when you create this PR, don't worry. You can edit this template as you're working on it.

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Necessary documentation (if appropriate) have been added / updated
- [x ] DCO signoffs have been added to all commits, including this PR

#### PR type
What type of changes does your PR introduce to Zowe? _Put an `x` in the box that applies to this PR. If you're unsure about any of them, don't hesitate to ask._ 
- [ ] Bugfix 
- [x] Feature 
- [ ] Other... Please describe:

#### Relevant issues

Fixes 

Depends on #1208 

#### Changes proposed in this PR

- This pull request implements the following feature:
Prompt user for PKCS11 token and label, then store APIML public key in given token using gskkyman

#### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

#### Does this PR do something the person installing Zowe should know about?

---
* Affected function: certificate setup *

---
* Description: prompt user for PKCS11 token and label *

---
* Part: _name of customizable file involved_  *

---
_multi-line description_

#### Is there a related doc issue or Pull Request? 

Doc issue/PR number:

### CODE REVIEW

**Comment by stevenhorsman** [comment]
PRs shouldn't go straight to master, but into the staging branch

**Comment by stevenhorsman** [comment]
You'll also need to be aware of trying to add backwards compatibility support if possible so that a keystore directory created with 1.9 will still work with 1.10. If this isn't possible this needs to be flagged up as a change that required the re-running of zowe-setup-certificates.sh

**Comment by plavjanik** [comment]
This change is dependent on #1208 and it requires re-running of `zowe-setup-certificates.sh` since it has to store the z/OSMF JWT public key in the case when z/OSMF is using JWT tokens.

**Comment by stevenhorsman** [comment]
Thanks @plavjanik - we'll need to make sure that the 'Does this PR do something the person installing Zowe should know about?' section is filled in in the next PR so that SMP/E gets that data and create a doc issue so that they can flag this up in the release notes

**Pull request closed without merging**
