### PR TITLE
Change script for generating keystore to use new APIML Certificate Management

### PR DESCRIPTION
**Pull request by plavjanik**

### CODE REVIEW

**Comment by Colin-Stone** [comment]
Where does the setup-apiml-certificates-template.sh file come from?.

**Comment by MarkAckert** [comment]
The scripts come from the api-layer installable package. Source here: https://github.com/zowe/api-layer/tree/master/zowe-install .

**Comment by Colin-Stone** [comment]
Great thanks Mark. I was running a part build on top of 0.9.3 so was missing those

**Comment by plavjanik** [comment]
Thank you, Mark, for answering it. The latest master build of the APIML has the script included.

**Pull request merged**
