### PR TITLE
WIP: add ZOWE_APIM_DISCOVERY_PORT to the zlux config

### PR DESCRIPTION
**Pull request by fkovinAtRocket**

### CODE REVIEW

**Comment by fkovinAtRocket** [comment]
@stevenhorsman  @1000TurquoisePogs  @dmitrynikolaev

**Comment by MarkAckert** [comment]
Is this PR still correct as-is? It's been around for a while, and when I check zluxserver.json, I see a separate port field:

```
"mediationLayer": {
      "server": {
        "gatewayPort": 7554, "hostname": "XXXXXXXX.XXXXXX",
        "port": 10011,
        "isHttps": false
      },
      "enabled": false
    }, 
```

**Comment by jackjia-ibm** [comment]
**After we have `staging` branch, this PR should be adjusted to merge to `staging` instead of `master`.**

**Comment by fkovinAtRocket** [comment]
@reetchow adding Reet since he's been working on it recently

**Pull request closed without merging**
