### PR TITLE
Add new log directory setting

### PR DESCRIPTION
**Pull request by stevenhorsman**
Signed-off-by: stevenhorsman <steven@uk.ibm.com>

#### PR type
- [X] Feature

#### Relevant issues
Implements #1268

#### Changes proposed in this PR
Create a unified place for all Zowe install/configure logs

#### Does this PR do something the person installing Zowe should know about?
Various zowe install and configuration scripts now have the option to add `-l <log_dir>` to give a specific log directory output

#### Is there a related doc issue or Pull Request? 
Doc issue: https://github.com/zowe/docs-site/issues/1133

### CODE REVIEW

**Comment by stevenhorsman** [comment]
@jackjia-ibm - are you able to take a lot at this PR please?
PTF test: https://wash.zowe.org:8443/job/zowe-install-test/view/change-requests/job/PR-1272/20/
Convenience test: https://wash.zowe.org:8443/job/zowe-install-test/view/change-requests/job/PR-1272/19/

**Comment by jackjia-ibm** [comment]
Thanks @stevenhorsman for the fix. The build and test all look good.

Extra thoughts,

- I saw many similar code of `source setup-log-dir.sh` to `echo "Log file created: ${LOG_FILE}"`, not sure if it makes better we define a function `ensure_log_file` in `setup-log-dir.sh` and call it like `ensure_log_file "zowe-install"` to create the log file target directory.
- Will anyone assign values for `zowe_root_dir`, `zowe_instance_dir`, `zowe_keystore_dir` and `zowe_logs_dir` with space in directory name? For example, `zowe_logs_dir: /u/myuser/zowe 1.10.0/logs`. This should be a really rare use case.

Anyway those don't really big issues since everything work as expected already.

**Comment by stevenhorsman** [comment]
Thanks for the suggestion JacK. I've updated based on that (and fixed the addcontext linting problem).
Builds https://wash.zowe.org:8443/job/zowe-install-test/view/change-requests/job/PR-1272/23/ and https://wash.zowe.org:8443/job/zowe-install-test/view/change-requests/job/PR-1272/24/
WRT point 2 - I think it's worth us testing directories with a space - probably manually to start with and can worry about whether we automate it later?

**Comment by jackjia-ibm** [comment]
Thanks Steve for the fix, including the test case (it was a quick fix for a security concern). Yes I agree point 2 is a little off topic and is not the purpose of this PR. We can test it out later.

**Pull request merged**
