### PR TITLE
ZWENOSEC - sample to remove security setup

### PR DESCRIPTION
**Pull request by OnnoVdT**
Signed-off-by: OnnoVdT <49648041+OnnoVdT@users.noreply.github.com>

Please check if your PR fulfills the following requirements. This is simply a reminder of what we are going to look for before merging your PR. If you don't know all of this information when you create this PR, don't worry. You can edit this template as you're working on it.

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Necessary documentation (if appropriate) have been added / updated
- [x] DCO signoffs have been added to all commits, including this PR

#### PR type
What type of changes does your PR introduce to Zowe? _Put an `x` in the box that applies to this PR. If you're unsure about any of them, don't hesitate to ask._ 
- [ ] Bugfix 
- [x] Feature 
- [ ] Other... Please describe:

#### Relevant issues

Fixes 974

#### Changes proposed in this PR

- provide new samplib member to remove security setup.

#### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

#### Does this PR do something the person installing Zowe should know about?

---
* Affected function: _general area of interest_ *

---
* Description: _1 line description_ *

---
* Part: _name of customizable file involved_  *

---
_multi-line description_

#### Is there a related doc issue or Pull Request? 

Doc issue/PR number:

### CODE REVIEW

**Comment by OnnoVdT** [comment]
This update includes undoing the dataset security introduced in pull request https://github.com/zowe/zowe-install-packaging/pull/993

**Comment by John-A-Davies** [comment]
I ran the JCL and I got some errors.

```
/* REMOVE ZOWE DATA SET PROTECTION ..........................
READY                                                        
READY                                                        
/* general data set protection                               
READY                                                        
  LISTDSD PREFIX(ZWE)   ALL                                  
ICH35005I NO DATASETS LISTED                                 
READY                                                        
  PERMIT 'ZWE.*.**'   CLASS(DATASET) DELETE ID(ZWEADMIN)     
IKJ56702I INVALID DATASET NAME, 'ZWE.*.**'                   
READY                                                        
  DELDSD 'ZWE.*.**'                                          
IKJ56702I INVALID DATASET NAME, 'ZWE.*.**'                   
READY                                                        
READY                                                        
/* HLQ stub                                                  
READY                                                        
  LISTGRP  ZWE   ALL                                         
IKJ56702I INVALID SEGMENT, ALL                               
READY                                                        
  DELGROUP ZWE                                               
IKJ56702I INVALID GROUP, ZWE                                 
READY                                                        
```

**Comment by John-A-Davies** [comment]
The name of the facility class for the xmem server is ZWES.IS, but you have ZWEX.IS
```
READY                                                      
  RLIST  FACILITY ZWEX.IS ALL                              
ICH13003I ZWEX.IS NOT FOUND                                
READY                                                      
  PERMIT ZWEX.IS CLASS(FACILITY) DELETE ID(ZWESVUSR)       
ICH06004I ZWEX.IS NOT DEFINED TO RACF                      
```

**Comment by OnnoVdT** [comment]
The dataset related errors are there because the matching dataset protection has just now been merged.
Good catch on the ZWEX.IS typo. I'm assuming this is also fixed in your copy of ZWESECUR, as I used the staging ZWESECUR as model.

**Comment by John-A-Davies** [comment]
The newer ZWESECUR JCL gave me this
```
/* general data set protection                                       */ 
READY                                                                   
  LISTDSD PREFIX(ZWE)   ALL                                             
ICH35005I NO DATASETS LISTED                                            
READY                                                                   
  ADDSD  'ZWE.*.**'   UACC(READ) DATA('Zowe')                           
IKJ56702I INVALID DATASET NAME, 'ZWE.*.**'                              
READY                                                                   
  PERMIT 'ZWE.*.**'   CLASS(DATASET) ACCESS(ALTER) ID(ZWEADMIN)         
IKJ56702I INVALID DATASET NAME, 'ZWE.*.**'                              
READY                                                                   
```

**Comment by John-A-Davies** [comment]
Yes, the ZWEX.IS typo is fixed in ZWESECUR.jcl

**Comment by John-A-Davies** [comment]
The following RDEFINEs do not have a corresponding RDELETE
```
  RDEFINE STARTED ** STDATA(USER(=MEMBER) GROUP(&STCGROUP.))
  RDEFINE STARTED &ZOWESTC..* -
  RDEFINE STARTED &XMEMSTC..* -
  RDEFINE STARTED &AUXSTC..* -
  RDEFINE FACILITY ZWES.IS UACC(NONE)
   RDEFINE UNIXPRIV SUPERUSER.FILESYS UACC(NONE)
  RDEFINE FACILITY BPX.DAEMON UACC(NONE)
  RDEFINE FACILITY BPX.SERVER UACC(NONE)
```
I'm only concerned about ZWES.IS

**Comment by OnnoVdT** [comment]
regarding the failure to define dataset security
* RACF requires that the HLQ is defined as userid or group. You didn't include the HLQ stub step, so I'm not sure it was executed (but I'm guessing it is)
* RACF has 2 modes for defining dataset profiles, with and without EGN (Enhanced Generic Naming). I'm guessing the system you worked with (Marist ?) did not enable EGN
check with TSO SETROPTS LIST
ENHANCED GENERIC NAMING IS IN EFFECT   
if it is not in effect, the profile name must be changed to ZWE.*

**Comment by John-A-Davies** [comment]
`ENHANCED GENERIC NAMING IS NOT IN EFFECT `

**Comment by John-A-Davies** [comment]
```
READY                                            
  LISTGRP ZWE           ALL                      
IKJ56702I INVALID SEGMENT, ALL                   
READY                                            
  LISTDSD PREFIX(ZWE)   ALL                      
ICH35005I NO DATASETS LISTED                     
READY                                            
  LISTUSER ZWE                                   
ICH30001I UNABLE TO LOCATE USER    ENTRY ZWE     
READY                                                                                    
```

**Comment by OnnoVdT** [comment]
I fixed the LISTGRP in ZWENOSEC (remove the ALL), but the same problem exists in the ZWESECUR update that was merged earleir today. Can you correct in your copy of ZWESECUR?

**Comment by OnnoVdT** [comment]
@John-A-Davies if we want ZWENOSEC to be in the Shopz FMID we have to make sure it is in the build that will be handed to Shopz for validation on Feb 4. After that no new members are allowed until the first PTF comes out.

**Comment by John-A-Davies** [comment]
Yes, we should incorporate ZWENOSEC immediately.

**Comment by John-A-Davies** [comment]
> 
> 
> I fixed the LISTGRP in ZWENOSEC (remove the ALL), but the same problem exists in the ZWESECUR update that was merged earleir today. Can you correct in your copy of ZWESECUR?

Yes, I will do that today.

**Comment by OnnoVdT** [comment]
ZWESECUR update is in PR https://github.com/zowe/zowe-install-packaging/pull/1037

**Pull request merged**
