### PR TITLE
ZWEKRING: Extract hostname and ip address to SET variables

### PR DESCRIPTION
**Pull request by vit-tomica**
Extract hostname and ip address to SET variables

Fixes 
https://github.com/zowe/zowe-install-packaging/issues/1611

### CODE REVIEW

**Comment by vit-tomica** [comment]
Successfully tested for RACF locally. 
I need to test it for ACF2 and Top Secret then it'll be ready for merging.

**Comment by stevenhorsman** [comment]
Without updating the ansible scripts the JCL change will break our current automation. @vit-tomica - do you want to look at this, or would you prefer I do it?

**Comment by vit-tomica** [comment]
OK, I see. I'll take a look at it tomorrow morning as I'm done for today. I don't mind if you handle that in the meantime :)

**Comment by stevenhorsman** [comment]
Keying test: https://wash.zowe.org:8443/view/Zowe/job/zowe-install-test/view/change-requests/job/PR-1618/4/
convenience test: https://wash.zowe.org:8443/view/Zowe/job/zowe-install-test/view/change-requests/job/PR-1618/2/

**Review by stevenhorsman — APPROVED** [review]

**Comment by vit-tomica** [comment]
@stevenhorsman  Tested for ACF2 and Top secret locally. Both tests are OK.

**Pull request merged**
