### PR TITLE
Build script updates. No dependencies on other updates.

### PR DESCRIPTION
**Pull request by OnnoVdT**
Signed-off-by: OnnoVdT <49648041+OnnoVdT@users.noreply.github.com>

### CODE REVIEW

**Comment by stevenhorsman** [comment]
These scripts are currently in the /smpe/pax/scripts directory. We shouldn't have 2 copies in the repo, so should they be moved from there and the references to those versions be updated to point to the new ones?

**Comment by OnnoVdT** [comment]
The SMP/E build, SMP/E install and convenience build all need to allocate a dataset, but are all separate entities. If they share code that is buried in one of them, it is not obvious that the code is shared, and any update to it will have a ripple effect outside the intended target. So either each ships their own copy that cans tart living its own life, or the shared is moved to a location for which it is more obvious it is shared.

**Comment by stevenhorsman** [comment]
> the shared code is moved to a location for which it is more obvious it is shared.
I think this should be the solution, but creating multiple copies of something that is supposed to be the same doesn't work, it's just a maintenance nightmare.

**Comment by OnnoVdT** [comment]
Going to move the scripts to a shared location. Must be coordinated with updates to smpe.sh scripts and scripts that create convenience pax and smpe.pax

**Pull request closed without merging**
