### PR TITLE
Add test configuration and cleanup for acf2 and tss security config

### LINKED ISSUE #1614: ZWESECUR not running on marist-2, 3
ZWESECUR doesn't run properly on marist-2 or marist-3 and it is set to RACF mode

eg. marist-2 job:systsprt:
```
/* activate FACILITY class for z/OS UNIX & Zowe XMEM profiles        */
 READY
   SETROPTS GENERIC(FACILITY)
 IRR418I RACF PRODUCT DISABLED: COMMAND ENDED.
 READY
   SETROPTS CLASSACT(FACILITY) RACLIST(FACILITY)
 IRR418I RACF PRODUCT DISABLED: COMMAND ENDED.
 READY
```

The jcl needs updating to pass in the correct security system and we also need to investigate the undo as the test configuration is clearly not valid

### PR DESCRIPTION
**Pull request by stevenhorsman**
#### Relevant issues
Fixes #1614 

#### Changes proposed in this PR
- Support running ZWESECUR with the correct security system parameters on all test machines
- Add extend racf security cleanup to acf2 and tss systems

### CODE REVIEW

**Comment by stevenhorsman** [comment]
convenience tests on multiple seciruty systems: https://wash.zowe.org:8443/view/Zowe/job/zowe-install-test/view/change-requests/job/PR-1748/2/
Examples from logs:
ZWESECUR on marist-3:
```
1/* started task for ZOWE main server                                 */
     READY
       TSS LIST(STC) PROCNAME(ZWESVSTC)  PREFIX
     ACCESSORID = *STC*     NAME       = STARTED-TASKS
     TYPE       = GLOBAL    SIZE       =     2816  BYTES
     CREATED    = 01/29/20  00:00  LAST MOD   = 10/****/20  08:20
     TSS0300I  LIST     FUNCTION SUCCESSFUL
     READY
       TSS ADD(STC) PROCNAME(ZWESVSTC)  ACID(ZWESVUSR)
     TSS0300I  ADD      FUNCTION SUCCESSFUL
     READY
       TSS ADD(ZWESVUSR)   FAC(STC)
```

ZWESECUR on marist-2:
```
* started task for ZOWE main server
     ?
     *
     ?
     SET CONTROL(GSO)
     ?
     INSERT STC.ZWESVSTC  LOGONID(ZWESVUSR)   GROUP(ZWEADMIN) STCID(ZWESVSTC)
      S0W1 / STC.ZWESVSTC LAST CHANGED BY ZOWEAD3 ON 10/****/20-09:44
                           GROUP(ZWEADMIN) LOGONID(ZWESVUSR) STCID(ZWESVSTC)
     ?
     F ACF2,REFRESH(STC)
     ACF79507 GSO PROCESSING COMPLETED WITHOUT ERROR
```

ptf tests: https://wash.zowe.org:8443/view/Zowe/job/zowe-install-test/view/change-requests/job/PR-1748/3/

**Comment by stevenhorsman** [comment]
@jackjia-ibm - is there any chance that you'll be able to review this soon as it's been waiting for a while? If not that's fine, but if you let me know then I can ask someone else. Thanks!

**Comment by jackjia-ibm** [comment]
@stevenhorsman sorry I must missed the notification. Will check today.

**Review by jackjia-ibm — APPROVED** [review]
Sorry for the delay. Changes look good to me. Also great fixes on <esm>-keyring.ts to remove zos_security_system assignments. Thanks.

**Pull request merged**
