### PR TITLE
Update v1 staging manifest sourceDependencies

### PR DESCRIPTION
**Pull request by FlappiTomic**
Signed-off-by: Tom Zhang <14881754+FlappiTomic@users.noreply.github.com>

Please check if your PR fulfills the following requirements. This is simply a reminder of what we are going to look for before merging your PR. If you don't know all of this information when you create this PR, don't worry. You can edit this template as you're working on it.

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Necessary documentation (if appropriate) have been added / updated
- [ ] DCO signoffs have been added to all commits, including this PR

#### PR type
What type of changes does your PR introduce to Zowe? _Put an `x` in the box that applies to this PR. If you're unsure about any of them, don't hesitate to ask._ 
- [ ] Bugfix 
- [ ] Feature 
- [ ] Other... Please describe:

#### Relevant issues

Fixes 

#### Changes proposed in this PR

- 

#### Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

#### Does this PR do something the person installing Zowe should know about?

---
* Affected function: _general area of interest_ *

---
* Description: _1 line description_ *

---
* Part: _name of customizable file involved_  *

---
_multi-line description_

#### Is there a related doc issue or Pull Request? 

Doc issue/PR number:

### CODE REVIEW

**Comment by FlappiTomic** [comment]
Hi all, there are a couple of repos that I am unable to determine the correct v1 staging/master branch. Some branch name is ambiguous as not reflecting dedicated v1; some repos have not gotten any active updates for a while. Therefore, I marked a `#FIXME` beside, please validate them and let me know. I attached links to each repo's branch page for your convenience.
This is for v1.

@t1m0thyj  
- [x] L248 [perf-timing](https://github.com/zowe/perf-timing/branches/all)
- [x] L262 [zowe-cli-scs-plugin](https://github.com/zowe/zowe-cli-scs-plugin/branches/all)

@balhar-jakub @CarsonCook 
- [ ]  L155 [api-layer](https://github.com/zowe/api-layer/branches/all)
- [ ]  L162 [common-java](https://github.com/zowe/common-java/branches/all)

@1000TurquoisePogs @struga0258 
- [x] L184 [zlux-grid](https://github.com/zowe/zlux-grid/branches/all)
- [x] L204 [zlux-widgets](https://github.com/zowe/zlux-widgets/branches/all)
- [x] L398 [zlux-workflow](https://github.com/zowe/zlux-workflow/branches/all)

@jackjia-ibm 
- [x] L406 [keyring-utilities](https://github.com/zowe/keyring-utilities/branches/all)

And L290 Orion editor component, I don’t know who is the developer on this component.

**Comment by jackjia-ibm** [comment]
Thanks Tom. keyring_utilities is a generic tool, it’s same for zowe v1 and v2.

**Review by AdarshdeepCheema — APPROVED** [review]

**Comment by t1m0thyj** [comment]
Thanks @FlappiTomic. For the CLI:
* perf-timing is a utility library that has not been updated in a while, so it's the same for Zowe v1 and v2
* zowe-cli-scs-plugin is v1 only because it was deprecated (merged into core CLI) in v2

**Review by t1m0thyj — APPROVED** [review]

**Comment by struga0258** [comment]
the following zlux-grid, zlux-widgets, and zlux-workflow have been renamed to match the same naming system we have which is v1.x/master.

**Comment by FlappiTomic** [comment]
api-layer and common-java will keep `master`, will be changed later.
orion-editor-component has not been an active project, keep `master` as well.

**Pull request merged**
